// Product catalog — swap price / desc / sizes here. `variants` maps each
// size to its real Shopify Storefront API variant ID (gid://...), which is
// what js/shopify-cart.js uses to add the item to a real Shopify cart and
// checkout. A product with no `variants` (or a missing size) can't be
// added to bag yet — see product.js's "Not available yet" fallback.

const PRODUCTS = [
  {
    id: 'sdmnsta',
    title: 'SDMNSTA',
    punjabi: 'ਖ਼ਾਲੀ ਥਾਂ ਭਰੋ',
    price: 75,
    image: 'assets/sdmnsta.png',
    desc: 'DISTRESSED · HEAVYWEIGHT · 100% COTTON TEEZ · QUALITY TO LAST YOU',
    sizes: ['S', 'M', 'L', 'XL'],
    soldSizes: [],
    cat: 'tees',
    status: 'new',
    // Release: 27 Sep 2026, 6:00 PM Pacific (PDT = UTC-7) — stored as an
    // absolute instant so it means the same thing in every timezone.
    dropsAt: '2026-09-28T01:00:00Z',
    variants: {
      S: 'gid://shopify/ProductVariant/52714632675602',
      M: 'gid://shopify/ProductVariant/52714632708370',
      L: 'gid://shopify/ProductVariant/52714632741138',
      XL: 'gid://shopify/ProductVariant/52714632773906',
    },
  },
  // GREY TONE COLLECTION — 9 pieces, linked to the real "GREY TONE TEEZ"
  // products in Shopify (matched to each design by photo).
  {
    id: 'grey-tone-1',
    title: 'Grey Tone Collection',
    punjabi: 'ਸਲੇਟੀ ਟੋਨ ਸੰਗ੍ਰਹਿ',
    price: 45,
    image: 'assets/grey-tone-summer-box.png',
    desc: 'Part of the Grey Tone Collection. Heavyweight cotton, oversized fit.',
    sizes: ['S', 'M', 'L', 'XL'],
    soldSizes: [],
    cat: 'tees',
    status: 'new',
    variants: {
      S: 'gid://shopify/ProductVariant/52547261890834',
      M: 'gid://shopify/ProductVariant/52547261923602',
      L: 'gid://shopify/ProductVariant/52547261956370',
      XL: 'gid://shopify/ProductVariant/52547261989138',
    },
  },
  {
    id: 'grey-tone-2',
    title: 'Grey Tone Collection',
    punjabi: 'ਸਲੇਟੀ ਟੋਨ ਸੰਗ੍ਰਹਿ',
    price: 45,
    image: 'assets/grey-tone-growing-trees.png',
    desc: 'Part of the Grey Tone Collection. Heavyweight cotton, oversized fit.',
    sizes: ['S', 'M', 'L', 'XL'],
    soldSizes: [],
    cat: 'tees',
    status: 'new',
    variants: {
      S: 'gid://shopify/ProductVariant/52547258908946',
      M: 'gid://shopify/ProductVariant/52547258941714',
      L: 'gid://shopify/ProductVariant/52547258974482',
      XL: 'gid://shopify/ProductVariant/52547259007250',
    },
  },
  {
    id: 'grey-tone-3',
    title: 'Grey Tone Collection',
    punjabi: 'ਸਲੇਟੀ ਟੋਨ ਸੰਗ੍ਰਹਿ',
    price: 45,
    image: 'assets/grey-tone-s7-video.png',
    desc: 'Part of the Grey Tone Collection. Heavyweight cotton, oversized fit.',
    sizes: ['S', 'M', 'L', 'XL'],
    soldSizes: [],
    cat: 'tees',
    status: 'new',
    variants: {
      S: 'gid://shopify/ProductVariant/52547259171090',
      M: 'gid://shopify/ProductVariant/52547259203858',
      L: 'gid://shopify/ProductVariant/52547259236626',
      XL: 'gid://shopify/ProductVariant/52547259269394',
    },
  },
  {
    id: 'grey-tone-4',
    title: 'Grey Tone Collection',
    punjabi: 'ਸਲੇਟੀ ਟੋਨ ਸੰਗ੍ਰਹਿ',
    price: 45,
    image: 'assets/grey-tone-handstyle.png',
    desc: 'Part of the Grey Tone Collection. Heavyweight cotton, oversized fit.',
    sizes: ['S', 'M', 'L', 'XL'],
    soldSizes: [],
    cat: 'tees',
    status: 'new',
    variants: {
      S: 'gid://shopify/ProductVariant/52547258581266',
      M: 'gid://shopify/ProductVariant/52547258614034',
      L: 'gid://shopify/ProductVariant/52547258646802',
      XL: 'gid://shopify/ProductVariant/52547258679570',
    },
  },
  {
    id: 'grey-tone-5',
    title: 'Grey Tone Collection',
    punjabi: 'ਸਲੇਟੀ ਟੋਨ ਸੰਗ੍ਰਹਿ',
    price: 45,
    image: 'assets/grey-tone-hand-signs.png',
    desc: 'Part of the Grey Tone Collection. Heavyweight cotton, oversized fit.',
    sizes: ['S', 'M', 'L', 'XL'],
    soldSizes: [],
    cat: 'tees',
    status: 'new',
    variants: {
      S: 'gid://shopify/ProductVariant/52547258286354',
      M: 'gid://shopify/ProductVariant/52547258319122',
      L: 'gid://shopify/ProductVariant/52547258351890',
      XL: 'gid://shopify/ProductVariant/52547258384658',
    },
  },
  {
    id: 'grey-tone-6',
    title: 'Grey Tone Collection',
    punjabi: 'ਸਲੇਟੀ ਟੋਨ ਸੰਗ੍ਰਹਿ',
    price: 45,
    image: 'assets/grey-tone-globe-spiral.png',
    desc: 'Part of the Grey Tone Collection. Heavyweight cotton, oversized fit.',
    sizes: ['S', 'M', 'L', 'XL'],
    soldSizes: [],
    cat: 'tees',
    status: 'new',
    variants: {
      S: 'gid://shopify/ProductVariant/52547262087442',
      M: 'gid://shopify/ProductVariant/52547262120210',
      L: 'gid://shopify/ProductVariant/52547262152978',
      XL: 'gid://shopify/ProductVariant/52547262185746',
    },
  },
  {
    id: 'grey-tone-7',
    title: 'Grey Tone Collection',
    punjabi: 'ਸਲੇਟੀ ਟੋਨ ਸੰਗ੍ਰਹਿ',
    price: 45,
    image: 'assets/grey-tone-search-globe.png',
    desc: 'Part of the Grey Tone Collection. Heavyweight cotton, oversized fit.',
    sizes: ['S', 'M', 'L', 'XL'],
    soldSizes: [],
    cat: 'tees',
    status: 'new',
    variants: {
      S: 'gid://shopify/ProductVariant/52547261497618',
      M: 'gid://shopify/ProductVariant/52547261530386',
      L: 'gid://shopify/ProductVariant/52547261563154',
      XL: 'gid://shopify/ProductVariant/52547261595922',
    },
  },
  {
    id: 'grey-tone-8',
    title: 'Grey Tone Collection',
    punjabi: 'ਸਲੇਟੀ ਟੋਨ ਸੰਗ੍ਰਹਿ',
    price: 45,
    image: 'assets/grey-tone-st-racing.png',
    desc: 'Part of the Grey Tone Collection. Heavyweight cotton, oversized fit.',
    sizes: ['S', 'M', 'L', 'XL'],
    soldSizes: [],
    cat: 'tees',
    status: 'new',
    variants: {
      S: 'gid://shopify/ProductVariant/52547257991442',
      M: 'gid://shopify/ProductVariant/52547258024210',
      L: 'gid://shopify/ProductVariant/52547258056978',
      XL: 'gid://shopify/ProductVariant/52547258089746',
    },
  },
  {
    id: 'grey-tone-9',
    title: 'Grey Tone Collection',
    punjabi: 'ਸਲੇਟੀ ਟੋਨ ਸੰਗ੍ਰਹਿ',
    price: 45,
    image: 'assets/grey-tone-dave-says.png',
    desc: 'Part of the Grey Tone Collection. Heavyweight cotton, oversized fit.',
    sizes: ['S', 'M', 'L', 'XL'],
    soldSizes: [],
    cat: 'tees',
    status: 'new',
    variants: {
      S: 'gid://shopify/ProductVariant/52547261694226',
      M: 'gid://shopify/ProductVariant/52547261726994',
      L: 'gid://shopify/ProductVariant/52547261759762',
      XL: 'gid://shopify/ProductVariant/52547261792530',
    },
  },
];
