// Product catalog — swap price / desc / sizes here. `variants` maps each
// size to its real Shopify Storefront API variant ID (gid://...), which is
// what js/shopify-cart.js uses to add the item to a real Shopify cart and
// checkout. A product with no `variants` (or a missing size) can't be
// added to bag yet — see product.js's "Not available yet" fallback.

const PRODUCTS = [
  // GREY TONE COLLECTION — 9 pieces, linked to the real "GREY TONE TEEZ"
  // products in Shopify (matched to each design by photo).
  {
    id: 'grey-tone-1',
    title: 'Grey Tone Collection',
    punjabi: 'ਸਲੇਟੀ ਟੋਨ ਸੰਗ੍ਰਹਿ',
    price: 45,
    image: 'assets/grey-tone-summer-box.png',
    desc: 'Part of the Grey Tone Collection. Heavyweight cotton, oversized fit.',
    sizes: ['S', 'M', 'L', 'XL'],
    soldSizes: [],
    cat: 'tees',
    status: 'new',
    variants: {
      S: 'gid://shopify/ProductVariant/52547261890834',
      M: 'gid://shopify/ProductVariant/52547261923602',
      L: 'gid://shopify/ProductVariant/52547261956370',
      XL: 'gid://shopify/ProductVariant/52547261989138',
    },
  },
  {
    id: 'grey-tone-2',
    title: 'Grey Tone Collection',
    punjabi: 'ਸਲੇਟੀ ਟੋਨ ਸੰਗ੍ਰਹਿ',
    price: 45,
    image: 'assets/grey-tone-growing-trees.png',
    desc: 'Part of the Grey Tone Collection. Heavyweight cotton, oversized fit.',
    sizes: ['S', 'M', 'L', 'XL'],
    soldSizes: [],
    cat: 'tees',
    status: 'new',
    variants: {
      S: 'gid://shopify/ProductVariant/52547258908946',
      M: 'gid://shopify/ProductVariant/52547258941714',
      L: 'gid://shopify/ProductVariant/52547258974482',
      XL: 'gid://shopify/ProductVariant/52547259007250',
    },
  },
  {
    id: 'grey-tone-3',
    title: 'Grey Tone Collection',
    punjabi: 'ਸਲੇਟੀ ਟੋਨ ਸੰਗ੍ਰਹਿ',
    price: 45,
    image: 'assets/grey-tone-s7-video.png',
    desc: 'Part of the Grey Tone Collection. Heavyweight cotton, oversized fit.',
    sizes: ['S', 'M', 'L', 'XL'],
    soldSizes: [],
    cat: 'tees',
    status: 'new',
    variants: {
      S: 'gid://shopify/ProductVariant/52547259171090',
      M: 'gid://shopify/ProductVariant/52547259203858',
      L: 'gid://shopify/ProductVariant/52547259236626',
      XL: 'gid://shopify/ProductVariant/52547259269394',
    },
  },
  {
    id: 'grey-tone-4',
    title: 'Grey Tone Collection',
    punjabi: 'ਸਲੇਟੀ ਟੋਨ ਸੰਗ੍ਰਹਿ',
    price: 45,
    image: 'assets/grey-tone-handstyle.png',
    desc: 'Part of the Grey Tone Collection. Heavyweight cotton, oversized fit.',
    sizes: ['S', 'M', 'L', 'XL'],
    soldSizes: [],
    cat: 'tees',
    status: 'new',
    variants: {
      S: 'gid://shopify/ProductVariant/52547258581266',
      M: 'gid://shopify/ProductVariant/52547258614034',
      L: 'gid://shopify/ProductVariant/52547258646802',
      XL: 'gid://shopify/ProductVariant/52547258679570',
    },
  },
  {
    id: 'grey-tone-5',
    title: 'Grey Tone Collection',
    punjabi: 'ਸਲੇਟੀ ਟੋਨ ਸੰਗ੍ਰਹਿ',
    price: 45,
    image: 'assets/grey-tone-hand-signs.png',
    desc: 'Part of the Grey Tone Collection. Heavyweight cotton, oversized fit.',
    sizes: ['S', 'M', 'L', 'XL'],
    soldSizes: [],
    cat: 'tees',
    status: 'new',
    variants: {
      S: 'gid://shopify/ProductVariant/52547258286354',
      M: 'gid://shopify/ProductVariant/52547258319122',
      L: 'gid://shopify/ProductVariant/52547258351890',
      XL: 'gid://shopify/ProductVariant/52547258384658',
    },
  },
  {
    id: 'grey-tone-6',
    title: 'Grey Tone Collection',
    punjabi: 'ਸਲੇਟੀ ਟੋਨ ਸੰਗ੍ਰਹਿ',
    price: 45,
    image: 'assets/grey-tone-globe-spiral.png',
    desc: 'Part of the Grey Tone Collection. Heavyweight cotton, oversized fit.',
    sizes: ['S', 'M', 'L', 'XL'],
    soldSizes: [],
    cat: 'tees',
    status: 'new',
    variants: {
      S: 'gid://shopify/ProductVariant/52547262087442',
      M: 'gid://shopify/ProductVariant/52547262120210',
      L: 'gid://shopify/ProductVariant/52547262152978',
      XL: 'gid://shopify/ProductVariant/52547262185746',
    },
  },
  {
    id: 'grey-tone-7',
    title: 'Grey Tone Collection',
    punjabi: 'ਸਲੇਟੀ ਟੋਨ ਸੰਗ੍ਰਹਿ',
    price: 45,
    image: 'assets/grey-tone-search-globe.png',
    desc: 'Part of the Grey Tone Collection. Heavyweight cotton, oversized fit.',
    sizes: ['S', 'M', 'L', 'XL'],
    soldSizes: [],
    cat: 'tees',
    status: 'new',
    variants: {
      S: 'gid://shopify/ProductVariant/52547261497618',
      M: 'gid://shopify/ProductVariant/52547261530386',
      L: 'gid://shopify/ProductVariant/52547261563154',
      XL: 'gid://shopify/ProductVariant/52547261595922',
    },
  },
  {
    id: 'grey-tone-8',
    title: 'Grey Tone Collection',
    punjabi: 'ਸਲੇਟੀ ਟੋਨ ਸੰਗ੍ਰਹਿ',
    price: 45,
    image: 'assets/grey-tone-st-racing.png',
    desc: 'Part of the Grey Tone Collection. Heavyweight cotton, oversized fit.',
    sizes: ['S', 'M', 'L', 'XL'],
    soldSizes: [],
    cat: 'tees',
    status: 'new',
    variants: {
      S: 'gid://shopify/ProductVariant/52547257991442',
      M: 'gid://shopify/ProductVariant/52547258024210',
      L: 'gid://shopify/ProductVariant/52547258056978',
      XL: 'gid://shopify/ProductVariant/52547258089746',
    },
  },
  {
    id: 'grey-tone-9',
    title: 'Grey Tone Collection',
    punjabi: 'ਸਲੇਟੀ ਟੋਨ ਸੰਗ੍ਰਹਿ',
    price: 45,
    image: 'assets/grey-tone-dave-says.png',
    desc: 'Part of the Grey Tone Collection. Heavyweight cotton, oversized fit.',
    sizes: ['S', 'M', 'L', 'XL'],
    soldSizes: [],
    cat: 'tees',
    status: 'new',
    variants: {
      S: 'gid://shopify/ProductVariant/52547261694226',
      M: 'gid://shopify/ProductVariant/52547261726994',
      L: 'gid://shopify/ProductVariant/52547261759762',
      XL: 'gid://shopify/ProductVariant/52547261792530',
    },
  },
  {
    id: 'holi-jacket',
    title: 'HOLI JACKET',
    punjabi: 'ਹੋਲੀ ਜੈਕਟ',
    price: 150,
    image: 'assets/holi-jacket.png',
    images: ['assets/holi-jacket.png', 'assets/holi-jacket-2.png', 'assets/holi-jacket-3.png'],
    desc: 'Heavyweight denim, silk-lined, with embroidered back and sleeves — the aftermath of Holi. Preorder now, ships in 3 weeks.',
    sizes: ['S', 'M', 'L', 'XL'],
    soldSizes: [],
    cat: 'outerwear',
    status: 'new',
    variants: {
      S: 'gid://shopify/ProductVariant/52547262316818',
      M: 'gid://shopify/ProductVariant/52551823360274',
      L: 'gid://shopify/ProductVariant/52551823393042',
      XL: 'gid://shopify/ProductVariant/52551823425810',
    },
  },
];
