// Product catalog — swap price / desc / sizes / add real image paths + Shopify variant IDs here.
// The `shopifyVariantId` field is what you'll use when you wire up Shopify (see product.html comment).

const PRODUCTS = [
  // GREY TONE COLLECTION — 9 pieces, all with real photos. Price is a
  // placeholder ($150, matching the rest of the catalog) — swap to the
  // real price per item.
  {
    id: 'grey-tone-1',
    title: 'Grey Tone Collection',
    punjabi: 'ਸਲੇਟੀ ਟੋਨ ਸੰਗ੍ਰਹਿ',
    price: 150,
    image: 'assets/grey-tone-summer-box.jpg',
    desc: 'Part of the Grey Tone Collection. Heavyweight cotton, oversized fit.',
    sizes: ['S', 'M', 'L', 'XL'],
    soldSizes: [],
    cat: 'tees',
    status: 'new',
    shopifyVariantId: null,
  },
  {
    id: 'grey-tone-2',
    title: 'Grey Tone Collection',
    punjabi: 'ਸਲੇਟੀ ਟੋਨ ਸੰਗ੍ਰਹਿ',
    price: 150,
    image: 'assets/grey-tone-growing-trees.jpg',
    desc: 'Part of the Grey Tone Collection. Heavyweight cotton, oversized fit.',
    sizes: ['S', 'M', 'L', 'XL'],
    soldSizes: [],
    cat: 'tees',
    status: 'new',
    shopifyVariantId: null,
  },
  {
    id: 'grey-tone-3',
    title: 'Grey Tone Collection',
    punjabi: 'ਸਲੇਟੀ ਟੋਨ ਸੰਗ੍ਰਹਿ',
    price: 150,
    image: 'assets/grey-tone-s7-video.jpg',
    desc: 'Part of the Grey Tone Collection. Heavyweight cotton, oversized fit.',
    sizes: ['S', 'M', 'L', 'XL'],
    soldSizes: [],
    cat: 'tees',
    status: 'new',
    shopifyVariantId: null,
  },
  {
    id: 'grey-tone-4',
    title: 'Grey Tone Collection',
    punjabi: 'ਸਲੇਟੀ ਟੋਨ ਸੰਗ੍ਰਹਿ',
    price: 150,
    image: 'assets/grey-tone-handstyle.jpg',
    desc: 'Part of the Grey Tone Collection. Heavyweight cotton, oversized fit.',
    sizes: ['S', 'M', 'L', 'XL'],
    soldSizes: [],
    cat: 'tees',
    status: 'new',
    shopifyVariantId: null,
  },
  {
    id: 'grey-tone-5',
    title: 'Grey Tone Collection',
    punjabi: 'ਸਲੇਟੀ ਟੋਨ ਸੰਗ੍ਰਹਿ',
    price: 150,
    image: 'assets/grey-tone-hand-signs.jpg',
    desc: 'Part of the Grey Tone Collection. Heavyweight cotton, oversized fit.',
    sizes: ['S', 'M', 'L', 'XL'],
    soldSizes: [],
    cat: 'tees',
    status: 'new',
    shopifyVariantId: null,
  },
  {
    id: 'grey-tone-6',
    title: 'Grey Tone Collection',
    punjabi: 'ਸਲੇਟੀ ਟੋਨ ਸੰਗ੍ਰਹਿ',
    price: 150,
    image: 'assets/grey-tone-globe-spiral.jpg',
    desc: 'Part of the Grey Tone Collection. Heavyweight cotton, oversized fit.',
    sizes: ['S', 'M', 'L', 'XL'],
    soldSizes: [],
    cat: 'tees',
    status: 'new',
    shopifyVariantId: null,
  },
  {
    id: 'grey-tone-7',
    title: 'Grey Tone Collection',
    punjabi: 'ਸਲੇਟੀ ਟੋਨ ਸੰਗ੍ਰਹਿ',
    price: 150,
    image: 'assets/grey-tone-search-globe.jpg',
    desc: 'Part of the Grey Tone Collection. Heavyweight cotton, oversized fit.',
    sizes: ['S', 'M', 'L', 'XL'],
    soldSizes: [],
    cat: 'tees',
    status: 'new',
    shopifyVariantId: null,
  },
  {
    id: 'grey-tone-8',
    title: 'Grey Tone Collection',
    punjabi: 'ਸਲੇਟੀ ਟੋਨ ਸੰਗ੍ਰਹਿ',
    price: 150,
    image: 'assets/grey-tone-st-racing.jpg',
    desc: 'Part of the Grey Tone Collection. Heavyweight cotton, oversized fit.',
    sizes: ['S', 'M', 'L', 'XL'],
    soldSizes: [],
    cat: 'tees',
    status: 'new',
    shopifyVariantId: null,
  },
  {
    id: 'grey-tone-9',
    title: 'Grey Tone Collection',
    punjabi: 'ਸਲੇਟੀ ਟੋਨ ਸੰਗ੍ਰਹਿ',
    price: 150,
    image: 'assets/grey-tone-dave-says.jpg',
    desc: 'Part of the Grey Tone Collection. Heavyweight cotton, oversized fit.',
    sizes: ['S', 'M', 'L', 'XL'],
    soldSizes: [],
    cat: 'tees',
    status: 'new',
    shopifyVariantId: null,
  },
];
